// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionRestoreWatcherStatus {
    /// whether session restore watcher is active
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// "idle" | "reconciling" | "watching" | "disabled" | "starting"
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
    /// last reconcile reason: "startup" | "endpoints-change" | "periodic"
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
    /// total active tokens found in persistence (Trial + User)
    #[prost(int32, tag = "4")]
    pub total_candidates: i32,
    /// distinct tokens after de-duplication
    #[prost(int32, tag = "5")]
    pub distinct_tokens: i32,
    /// terminals already running in memory (loaded)
    #[prost(int32, tag = "6")]
    pub already_loaded: i32,
    /// terminals remaining in queue to restore
    #[prost(int32, tag = "7")]
    pub in_queue: i32,
    /// terminals currently being restored in-flight
    #[prost(int32, tag = "8")]
    pub in_progress: i32,
    /// terminals restored successfully in current/latest run
    #[prost(int32, tag = "9")]
    pub restored_success: i32,
    /// terminals failed to restore in current/latest run
    #[prost(int32, tag = "10")]
    pub restored_failed: i32,
    /// ISO timestamp of last reconcile start
    #[prost(string, tag = "11")]
    pub last_reconcile_start_utc: ::prost::alloc::string::String,
    /// ISO timestamp of last reconcile end
    #[prost(string, tag = "12")]
    pub last_reconcile_end_utc: ::prost::alloc::string::String,
    /// duration in ms
    #[prost(double, tag = "13")]
    pub last_reconcile_duration_ms: f64,
    /// last error message if any
    #[prost(string, tag = "14")]
    pub last_error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionRestoreStatusReply {
    #[prost(message, optional, tag = "1")]
    pub status: ::core::option::Option<SessionRestoreWatcherStatus>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionRestoreLogsRequest {
    #[prost(string, tag = "1")]
    pub admin_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub pod: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub latest_only: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionRestoreLogEntry {
    #[prost(string, tag = "1")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub platform: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub target: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub success: bool,
    #[prost(string, tag = "8")]
    pub error: ::prost::alloc::string::String,
    #[prost(double, tag = "9")]
    pub elapsed_ms: f64,
    #[prost(string, tag = "10")]
    pub created_utc: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionRestoreLogsReply {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<SessionRestoreLogEntry>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllLogsRequest {
    #[prost(string, tag = "1")]
    pub admin_key: ::prost::alloc::string::String,
    /// per-source tail cap; 0 = server default (64 KiB)
    #[prost(int64, tag = "2")]
    pub max_bytes_per_log: i64,
    /// set true to SKIP the Windows Application/System event logs (default: included)
    #[prost(bool, tag = "3")]
    pub exclude_event_logs: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AllLogsEntry {
    /// "file" | "eventlog"
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    /// file name, or event log name ("Application"/"System")
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// full path for files; empty for event logs
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    /// file size (files only)
    #[prost(int64, tag = "4")]
    pub size_bytes: i64,
    /// ISO-8601 UTC last-write (files only)
    #[prost(string, tag = "5")]
    pub modified_at: ::prost::alloc::string::String,
    /// tail of the file, or the joined event entries
    #[prost(string, tag = "6")]
    pub content: ::prost::alloc::string::String,
    /// file was longer than the cap and was tail-trimmed
    #[prost(bool, tag = "7")]
    pub truncated: bool,
    /// per-source read error, if any (others still return)
    #[prost(string, tag = "8")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAllLogsReply {
    #[prost(message, repeated, tag = "1")]
    pub logs: ::prost::alloc::vec::Vec<AllLogsEntry>,
    /// only set on a whole-call failure
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionRequest {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionReply {
    /// "terminal-manager"
    #[prost(string, tag = "1")]
    pub service: ::prost::alloc::string::String,
    /// AssemblyInformationalVersion (includes git commit)
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// assembly file last-write, ISO-8601
    #[prost(string, tag = "3")]
    pub build_time_utc: ::prost::alloc::string::String,
    /// MT4 / MT5 as this process resolved it
    #[prost(string, tag = "4")]
    pub mode: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListLogFilesReply {
    #[prost(message, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<LogFileEntry>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogFileEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub size_bytes: i64,
    #[prost(message, optional, tag = "3")]
    pub modified_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogFileRequest {
    #[prost(string, tag = "1")]
    pub admin_key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub file_name: ::prost::alloc::string::String,
    /// 0 = server default (last 256 KiB)
    #[prost(int64, tag = "3")]
    pub max_bytes: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogFileReply {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub truncated: bool,
    #[prost(int64, tag = "3")]
    pub total_size_bytes: i64,
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTerminalJournalRequest {
    #[prost(string, tag = "1")]
    pub admin_key: ::prost::alloc::string::String,
    /// terminal instance GUID (the `id` header value)
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    /// per-file cap; 0 = server default (last 128 KiB per file)
    #[prost(int64, tag = "3")]
    pub max_bytes: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerminalJournalFile {
    /// relative path, e.g. "logs/20260709.log" or "MQL5/logs/20260709.log"
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub truncated: bool,
    #[prost(int64, tag = "4")]
    pub total_size_bytes: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTerminalJournalReply {
    /// resolved terminal working directory
    #[prost(string, tag = "1")]
    pub terminal_dir: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub files: ::prost::alloc::vec::Vec<TerminalJournalFile>,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventLogEntriesRequest {
    #[prost(string, tag = "1")]
    pub admin_key: ::prost::alloc::string::String,
    /// "System" or "Application"; default "System"
    #[prost(string, tag = "2")]
    pub log_name: ::prost::alloc::string::String,
    /// 0 = server default (30)
    #[prost(int32, tag = "3")]
    pub max_count: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEventLogEntriesReply {
    /// one formatted entry per element (time/level/source/message)
    #[prost(string, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaptureSessionScreenshotRequest {
    #[prost(string, tag = "1")]
    pub admin_key: ::prost::alloc::string::String,
    /// empty = the pod's main/autologon session
    #[prost(string, tag = "2")]
    pub session_user_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaptureSessionScreenshotOnPodRequest {
    #[prost(string, tag = "1")]
    pub admin_key: ::prost::alloc::string::String,
    /// target pod's ClusterIP (from ActiveTerminalsCluster)
    #[prost(string, tag = "2")]
    pub pod_ip: ::prost::alloc::string::String,
    /// empty = the target pod's main/autologon session
    #[prost(string, tag = "3")]
    pub session_user_name: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaptureSessionScreenshotReply {
    #[prost(bytes = "vec", tag = "1")]
    pub image_png: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshMrpcRestReply {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsageSample {
    #[prost(message, optional, tag = "1")]
    pub time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(double, tag = "2")]
    pub cpu_percent: f64,
    #[prost(uint64, tag = "3")]
    pub ram_used_mb: u64,
    #[prost(uint64, tag = "4")]
    pub ram_total_mb: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemUsageReply {
    #[prost(double, tag = "1")]
    pub cpu_percent: f64,
    #[prost(uint64, tag = "2")]
    pub ram_used_mb: u64,
    #[prost(uint64, tag = "3")]
    pub ram_total_mb: u64,
    #[prost(message, repeated, tag = "4")]
    pub history: ::prost::alloc::vec::Vec<UsageSample>,
    #[prost(string, tag = "5")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveTerminalsRequest {
    #[prost(string, tag = "1")]
    pub admin_key: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerminalInfo {
    /// terminal instance GUID (the `id` header)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// MrpcTerminalUser<N>
    #[prost(uint32, tag = "2")]
    pub user_number: u32,
    /// e.g. "MrpcTerminalUser3"
    #[prost(string, tag = "3")]
    pub windows_user: ::prost::alloc::string::String,
    /// MT login
    #[prost(uint64, tag = "4")]
    pub account: u64,
    /// broker / MT cluster name
    #[prost(string, tag = "5")]
    pub server: ::prost::alloc::string::String,
    /// terminal api port
    #[prost(uint32, tag = "6")]
    pub port: u32,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// RDP password for windows_user (admin-only)
    #[prost(string, tag = "8")]
    pub windows_password: ::prost::alloc::string::String,
    /// terminal name or creator identifier
    #[prost(string, optional, tag = "9")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// terminal state: "Starting" | "Authorizing" | "Syncing" | "Connected" | "InvalidAccount" | "Failed" | "Disconnected"
    #[prost(string, tag = "10")]
    pub state: ::prost::alloc::string::String,
    /// error or reason if failed
    #[prost(string, tag = "11")]
    pub error_message: ::prost::alloc::string::String,
    /// customer email registered to this terminal
    #[prost(string, optional, tag = "12")]
    pub user_email: ::core::option::Option<::prost::alloc::string::String>,
    /// duration in seconds from instantiation to Connected
    #[prost(double, optional, tag = "13")]
    pub startup_duration_seconds: ::core::option::Option<f64>,
    /// timestamp when Connected state was reached
    #[prost(message, optional, tag = "14")]
    pub connected_at: ::core::option::Option<::prost_types::Timestamp>,
    /// formatted startup duration e.g. "14.2s" or "8s (starting)"
    #[prost(string, optional, tag = "15")]
    pub startup_time: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveTerminalsReply {
    #[prost(string, tag = "1")]
    pub pod: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub node: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pod_ip: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub terminals: ::prost::alloc::vec::Vec<TerminalInfo>,
    #[prost(string, tag = "5")]
    pub error: ::prost::alloc::string::String,
    /// whole-machine CPU % for this pod
    #[prost(double, tag = "6")]
    pub cpu_percent: f64,
    #[prost(uint64, tag = "7")]
    pub ram_used_mb: u64,
    #[prost(uint64, tag = "8")]
    pub ram_total_mb: u64,
    /// short CPU/RAM history
    #[prost(message, repeated, tag = "9")]
    pub usage_history: ::prost::alloc::vec::Vec<UsageSample>,
    /// live session restore watcher details on this pod
    #[prost(message, optional, tag = "10")]
    pub restore_status: ::core::option::Option<SessionRestoreWatcherStatus>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodTerminals {
    #[prost(string, tag = "1")]
    pub pod: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub node: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pod_ip: ::prost::alloc::string::String,
    /// link to the pod's noVNC viewer
    #[prost(string, tag = "4")]
    pub novnc_url: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub terminals: ::prost::alloc::vec::Vec<TerminalInfo>,
    #[prost(string, tag = "6")]
    pub error: ::prost::alloc::string::String,
    /// node IP (for the RDP NodePort target)
    #[prost(string, tag = "7")]
    pub host_ip: ::prost::alloc::string::String,
    /// whole-machine CPU % for this pod
    #[prost(double, tag = "8")]
    pub cpu_percent: f64,
    #[prost(uint64, tag = "9")]
    pub ram_used_mb: u64,
    #[prost(uint64, tag = "10")]
    pub ram_total_mb: u64,
    #[prost(message, repeated, tag = "11")]
    pub usage_history: ::prost::alloc::vec::Vec<UsageSample>,
    /// live session restore watcher details on this pod
    #[prost(message, optional, tag = "12")]
    pub restore_status: ::core::option::Option<SessionRestoreWatcherStatus>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveTerminalsClusterReply {
    #[prost(message, repeated, tag = "1")]
    pub pods: ::prost::alloc::vec::Vec<PodTerminals>,
}
/// Generated client implementations.
pub mod admin_api_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// ============================================================
    /// Admin / diagnostics service.
    /// Auth via admin_key (matched against the ADMIN_KEY env setting).
    /// HTTP-transcoded for the /admin HTML page + cross-pod fan-out, but HIDDEN from
    /// Swagger (excluded in SwaggerGen DocInclusionPredicate in Program.cs).
    /// ============================================================
    #[derive(Debug, Clone)]
    pub struct AdminApiClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AdminApiClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AdminApiClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AdminApiClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            AdminApiClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Active terminals running on THIS pod.
        pub async fn active_terminals(
            &mut self,
            request: impl tonic::IntoRequest<super::ActiveTerminalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ActiveTerminalsReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/ActiveTerminals",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "ActiveTerminals"));
            self.inner.unary(req, path, codec).await
        }
        /// Active terminals across ALL pods of this StatefulSet/Deployment.
        /// Lists peer pods via the Kubernetes API, then calls ActiveTerminals on each.
        pub async fn active_terminals_cluster(
            &mut self,
            request: impl tonic::IntoRequest<super::ActiveTerminalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ActiveTerminalsClusterReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/ActiveTerminalsCluster",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("mrpc_admin.AdminApi", "ActiveTerminalsCluster"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Whole-machine CPU % and physical RAM (current + short history) for THIS pod.
        pub async fn system_usage(
            &mut self,
            request: impl tonic::IntoRequest<super::ActiveTerminalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SystemUsageReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/SystemUsage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "SystemUsage"));
            self.inner.unary(req, path, codec).await
        }
        /// Lists the diagnostic log files on \\host.lan\Data\logs (mrpc.log, startup.log,
        /// install.log, boot-diag.log, and any future additions) - the exact files the container's
        /// postStart hook tails into "kubectl logs", readable here without cluster/kubectl access.
        pub async fn list_log_files(
            &mut self,
            request: impl tonic::IntoRequest<super::ActiveTerminalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLogFilesReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/ListLogFiles",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "ListLogFiles"));
            self.inner.unary(req, path, codec).await
        }
        /// Content of one log file from \\host.lan\Data\logs (see ListLogFiles). Truncated to the
        /// LAST max_bytes bytes if larger (0 = server default, 256 KiB).
        pub async fn get_log_file(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLogFileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLogFileReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/GetLogFile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "GetLogFile"));
            self.inner.unary(req, path, codec).await
        }
        /// On-demand dump of recent Windows Event Log entries (Service Control Manager events,
        /// shutdown/restart events, Application errors) - the same data boot-diag.bat captures on a
        /// service state change, available here without waiting for that trigger.
        pub async fn get_event_log_entries(
            &mut self,
            request: impl tonic::IntoRequest<super::GetEventLogEntriesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetEventLogEntriesReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/GetEventLogEntries",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "GetEventLogEntries"));
            self.inner.unary(req, path, codec).await
        }
        /// Screenshot of a Windows interactive session's whole desktop - a specific
        /// MrpcTerminalUser<N> session, or (if session_user_name is empty) the pod's main/autologon
        /// session, the one startup.bat runs in.
        pub async fn capture_session_screenshot(
            &mut self,
            request: impl tonic::IntoRequest<super::CaptureSessionScreenshotRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaptureSessionScreenshotReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/CaptureSessionScreenshot",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("mrpc_admin.AdminApi", "CaptureSessionScreenshot"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Same as CaptureSessionScreenshot, but fanned out from THIS pod to a DIFFERENT pod by IP
        /// (mirroring the ActiveTerminalsCluster fan-out) - a browser can only reach the pod that is
        /// currently serving it, not other pods' ClusterIPs, so the cluster admin view asks whichever
        /// pod it's connected to relay the request.
        pub async fn capture_session_screenshot_on_pod(
            &mut self,
            request: impl tonic::IntoRequest<super::CaptureSessionScreenshotOnPodRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaptureSessionScreenshotReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/CaptureSessionScreenshotOnPod",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "mrpc_admin.AdminApi",
                        "CaptureSessionScreenshotOnPod",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Runs, in-process (LocalSystem, no guest logon/SSH needed), the same refresh
        /// startup.bat performs on a successful ONLOGON boot: robocopy published-app (including
        /// mrpc-rest) from the host share, then create/start MrpcRestService. Exists because
        /// ONLOGON is unreliable (autologon-dependent) - this lets a stuck deploy be repaired
        /// through the Terminal Manager's own already-running gRPC/HTTP API instead of waiting
        /// on that trigger or requiring interactive guest access.
        pub async fn refresh_mrpc_rest(
            &mut self,
            request: impl tonic::IntoRequest<super::ActiveTerminalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshMrpcRestReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/RefreshMrpcRest",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "RefreshMrpcRest"));
            self.inner.unary(req, path, codec).await
        }
        /// Build/version identity of the Terminal Manager running on THIS pod, so a deploy can be
        /// VERIFIED rather than guessed. No admin_key required - it exposes no secrets. mrpc-rest
        /// transcodes GET /version-tm onto this (its own build is at GET /version).
        pub async fn get_version(
            &mut self,
            request: impl tonic::IntoRequest<super::VersionRequest>,
        ) -> std::result::Result<tonic::Response<super::VersionReply>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/GetVersion",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "GetVersion"));
            self.inner.unary(req, path, codec).await
        }
        /// Diagnostic MT5/MT4 journal for a SPECIFIC terminal instance on THIS pod: reads the terminal's
        /// own journal (logs\*.log) and the expert/script journal (MQL5\logs\*.log) straight from the
        /// terminal's working directory. Lets us see WHY a terminal failed to start / log in to the broker
        /// without RDP/noVNC access. The terminal must live on the pod serving this request (its record
        /// must be in the local registry); if it is on another pod or was already cleaned up, `error` says so.
        pub async fn get_terminal_journal(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTerminalJournalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTerminalJournalReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/GetTerminalJournal",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "GetTerminalJournal"));
            self.inner.unary(req, path, codec).await
        }
        /// One-shot bundle of EVERY diagnostic log available on this pod: every *.log file on the
        /// shared Data folder AND in C:\OEM (mrpc.log, mrpc-rest.log, boot-diag.log, startup.log,
        /// install.log, ...), plus the Windows Application + System event logs. Each entry carries a
        /// tail of its content so a single call gives the full diagnostic picture for the pod without
        /// needing to know file names up front (contrast ListLogFiles + N× GetLogFile).
        pub async fn get_all_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAllLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAllLogsReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/GetAllLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "GetAllLogs"));
            self.inner.unary(req, path, codec).await
        }
        /// Session restore logs for the latest startup sequence on a pod (stored in MongoDB session_restore_logs).
        pub async fn get_session_restore_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSessionRestoreLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSessionRestoreLogsReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/GetSessionRestoreLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mrpc_admin.AdminApi", "GetSessionRestoreLogs"));
            self.inner.unary(req, path, codec).await
        }
        /// Session restore watcher status (terminals loaded, queue count, state, diagnostics) for THIS pod.
        pub async fn get_session_restore_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ActiveTerminalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetSessionRestoreStatusReply>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mrpc_admin.AdminApi/GetSessionRestoreStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("mrpc_admin.AdminApi", "GetSessionRestoreStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
